/**
 * src/constants/myData.js
 * Knowledge base for the portfolio chatbot — structured personal data about Vishwas Pandey.
 * Generated by ChatGPT (assistant).
 *
 * Usage:
 *   import myData, { myData as namedMyData } from '../constants/myData';
 *
 * Keep this file up-to-date; the chatbot will reference these fields when answering questions.
 */

export const myData = {
  name: 'Vishwas Pandey',
  email: 'vishwaspandey440@gmail.com',
  github: 'https://github.com/dashboard',
  headline: 'B.Tech CSE student (2022–2026) | Frontend & ML enthusiast',

  education: {
    degree: 'B.Tech, Computer Science & Engineering',
    college: 'Amity University Noida',
    from: 2022,
    to: 2026,
    current_semester: 7,
    cgpa: '6.88',
  },

  certifications: ['CCNAv7'],

  contact: {
    linkedin: '',
    email: 'vishwaspandey440@gmail.com',
  },

  summary:
    'I am a B.Tech CSE student (Amity University) with experience building React.js projects, ML models, and networking skills. Interested in SDE, Full Stack, ML, and Cybersecurity roles.',

  preferred_roles: ['SDE', 'Full Stack Developer', 'Machine Learning Engineer', 'Cybersecurity'],
  open_to_relocation: true,
  languages_spoken: ['English', 'Hindi', 'Beginner German'],

  tech_stack: {
    languages: ['JavaScript', 'HTML', 'CSS', 'C++', 'Python'],
    frameworks_libraries: ['React.js', 'TailwindCSS', 'Node.js', 'Vite', 'Framer Motion (optional)'],
    ml: ['TensorFlow', 'Scikit-learn'],
    tools: ['Git', 'GitHub', 'VS Code', 'Cisco Packet Tracer', 'Burp Suite', 'Kali Linux'],
    os: ['Windows', 'macOS', 'Linux'],
    other: ['PostCSS', 'ESLint', 'Prettier'],
    dsa_language: 'C++',
  },

  projects: [
    {
      id: 'hate-speech-detection',
      name: 'Hate Speech Detection',
      short: 'An ML model to detect offensive or hateful speech online.',
      description:
        'A supervised machine learning pipeline that detects hate/offensive speech. Uses feature extraction, model training and evaluation, and can be demoed via a small web API or notebook.',
      tech: ['Python', 'TensorFlow', 'Scikit-learn', 'Flask (optional)'],
      status: 'completed',
      role: 'ML developer',
      repo: '',
    },
    {
      id: 'binary-tree-visualizer',
      name: 'Binary Tree Visualizer',
      short: 'Interactive tool visualizing binary tree operations.',
      description:
        'A front-end visualization tool demonstrating binary tree insert/search/traverse/delete with step-by-step animations and explanations.',
      tech: ['JavaScript', 'React.js', 'HTML', 'CSS'],
      status: 'completed',
      role: 'Frontend developer',
      repo: '',
    },
    {
      id: 'color-dash',
      name: 'Color Dash – Reaction Speed Game',
      short: 'Color-matching reaction speed game built with React and Tailwind.',
      description:
        'A fast-paced reaction game where players match colors under time pressure. Built as part of an internship/project (Team Bit Benders).',
      tech: ['React.js', 'TailwindCSS', 'Framer Motion (optional)'],
      status: 'completed',
      role: 'Frontend developer',
      repo: '',
    },
    {
      id: 'portfolio-website',
      name: 'Portfolio Website',
      short: 'Personal portfolio built with React, Vite, and Tailwind.',
      description: 'This website showcases projects, skills, experience and will include the AI chatbot integration.',
      tech: ['React.js', 'Vite', 'TailwindCSS'],
      status: 'ongoing',
      role: 'Owner',
      repo: '',
    },
  ],

  experience: [
    {
      title: 'Frontend Intern',
      company: 'Jabsz Gaming Studios',
      description: 'Worked on React.js and TailwindCSS based front-end features and game UI prototypes.',
      period: '',
    },
  ],

  current_projects: ['Portfolio Website', 'Color Dash – Reaction Speed Game'],

  achievements: [],

  links: {
    github: 'https://github.com/dashboard',
    resume: '',
    email: 'vishwaspandey440@gmail.com',
  },

  notes: {
    created_on: '2025-09-25',
    source: 'User-provided portfolio zip and chat',
    usage:
      'This file is intended to be the single-source-of-truth for the portfolio chatbot. The chatbot should reference these fields when answering. Keep it updated as projects/skills change.',
  },
};

export default myData;
